### ISSUE TITLE
Respect comments

### ISSUE THREAD

**Issue by djui** [EddyLuten/line-breaker#1]
In case the line is a comment (either line or block) one might want to preserve broken lines as comments:

```
// foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar
```
Into
```
// foo bar foo bar foo bar foo bar foo bar foo bar foo bar
// foo bar foo bar foo bar foo bar foo bar
```
Instead
```
// foo bar foo bar foo bar foo bar foo bar foo bar foo bar
foo bar foo bar foo bar foo bar foo bar
```

Aswell as
```
/*
foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar
*/
```
Into
```
/*
foo bar foo bar foo bar foo bar foo bar foo bar foo bar
foo bar foo bar foo bar foo bar foo bar
*/
```

**Comment by EddyLuten** [comment]
Hi @djui sounds like a plan. I will try to get some familiarity with [Atom's language mode](https://github.com/atom/atom/blob/master/src/language-mode.coffee) and implement it.

**Comment by EddyLuten** [comment]
I've implemented the ability to break up lines of line comments and selections of line comments in the latest version, 0.3.0.

However, block comments are not supported since Atom does not have the ability to toggle block comments at this time. Implementing the toggling of block comments is out of the scope of this project, but I will add it as soon as Atom itself supports it through its language mode mechanism.

**Comment by djui** [comment]
Thanks for the quick turn-around, works!

**Comment by EddyLuten** [comment]
No worries, I'm glad you find the package useful!

**Comment by EddyLuten** [comment]
Follow up: as of the latest version, block comments are now also supported.
